### PR TITLE
fix: add `freeaddrinfo(res)` to prevent memory leak

### LINKED ISSUE #17: Add `freeaddrinfo(res)` to prevent memory leak after `getaddrinfo` in `create_connection()` and `create_socket()`
**Description**:  
There is a potential memory leak in both `create_connection()` and `create_socket()` functions due to missing calls to `freeaddrinfo(res)` after resolving addresses using `getaddrinfo`. The `getaddrinfo` function dynamically allocates memory for the `addrinfo` structure, and failing to free it can lead to memory leaks.

**Steps to Reproduce**:  
1. Call `create_connection()` or `create_socket()` in a loop or multiple times.
2. Monitor memory usage using tools like `valgrind` or `top` to observe memory leak.

**Expected Behavior**:  
Memory allocated by `getaddrinfo()` should be freed after it's no longer needed by calling `freeaddrinfo(res)`.

**Actual Behavior**:  
`freeaddrinfo(res)` is missing in some code paths in both functions, leading to memory not being freed, which can accumulate over time.

**Relevant Code**:  

In `create_connection()`:
```c
if (getaddrinfo(remote_host, portstr, &hints, &res) != 0) {
    errno = EFAULT;
    return CLIENT_RESOLVE_ERROR;
}

// freeaddrinfo(res) is not called in case of success or failure.
```

In `create_socket()`:
```c
if (getaddrinfo(bind_addr, portstr, &hints, &res) != 0) {
    return CLIENT_RESOLVE_ERROR;
}

// Missing freeaddrinfo(res) if bind or socket creation fails.
```

**Proposed Fix**:  
1. Add `freeaddrinfo(res)` after the socket connection is established or in failure cases where it is missing.
2. Make sure the `addrinfo` structure is freed before the function returns to prevent memory leaks.

**Priority**: Medium  
**Severity**: Memory Leak

### PR DESCRIPTION
**Pull request by thegauravgiri**
This PR fixes #17 

## Changes:
- add `freeaddrinfo(res)` at conditions that returns for the function without freeing the memory.

### CODE REVIEW

File: proxy.c [hunk 1]
```diff
@@ -228,20 +228,23 @@ int create_socket(int port) {
...
 
-
     if (setsockopt(server_sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval)) < 0) {
+        freeaddrinfo(res);
         return SERVER_SETSOCKOPT_ERROR;
     }
 
     if (bind(server_sock, res->ai_addr, res->ai_addrlen) == -1) {
-            close(server_sock);
+        close(server_sock);
```
Comment (kklis) [inline proxy.c:241]: @gaurovgiri I think `freeaddrinfo(res)` should also be used here after `close(server_sock)`, right? Please correct me if I'm missing something.

**Review by kklis — CHANGES_REQUESTED** [review]

File: proxy.c (hunk 1 above)
Comment (gaurovgiri) [reply proxy.c:241]: oh yes, you are right. I will fix it

Comment (gaurovgiri) [reply proxy.c:241]: I've updated the code
